### PR TITLE
Added dev data for testing and validating functions

### PR DESCRIPTION
**Pull request by isaak-willett**
# Overview:
Added two json files containing ROIs to build croissant functionality upon. Total ROIs is 100 between the two files with dev_training_rois containing 70 ROIs and dev_test_rois containing 30 ROIs. This ROI data will be used to create functions and do not reflect actual training or testing.

# Methodology
I took the first 100 ROIs from the Segmentation Labeling database, I then went backward to ophys session, through ophys experiment id, to get the metadata required. Wayne gave me a nice query that got all the required data through the ophys session id. I then downsampled the traces stored in the Segmentation Labeling database by the average strategy from 31Hz to 4Hz. The traces were then sliced to take 1/10th of their original length. As the ROIs were not production ROIs they were unlabelled so I used a seeded random to randomly generate a binary classification for each ROI. I also did NOT use Df/F traces as this is just dev data it doesn't really matter as it is the same format.

This process was performed for each of the 100 queried ROIs and the data for each was compiled into a dictionary for each ROI. This was added to a list that was split 70/30 train v test and written to a json file. The script that produced this output is shown below. Each ROI was queried by it's ROI_id whereas it should have been a bulk query of the first 100 but it works either way.
```
import json
import random

import numpy as np

import slapp.rois as roi_module
from slapp.transforms.array_utils import downsample_array
import slapp.utils.query_utils as query_utils

default_conn_variables = query_utils.label_defaults
db_credentials = query_utils.get_db_credentials(**default_conn_variables)
db_conn = query_utils.DbConnection(**db_credentials)
lims_conn = query_utils.DbConnection("LIMS CREDENTIALS")

seed = random.seed(0)
rois = []
for roi_id in range(1574255, 1574355):
    roi_dict = {}
    roi = db_conn.query(f"SELECT * FROM rois WHERE id={roi_id}")[0]
    segmentation_run = db_conn.query(("SELECT * FROM segmentation_runs WHERE "
                                      f"id={roi['segmentation_run_id']}"))[0]
    ophys_experiment_id = segmentation_run['ophys_experiment_id']
    ophys_session_id = lims_conn.query("SELECT ophys_session_id from ophys_experiments"
                                       f" WHERE id={ophys_experiment_id}")[0]['ophys_session_id']
    meta_data = lims_conn.query("SELECT e.name AS rig, i.depth, st.acronym AS targeted_structure," 
    " d.full_genotype FROM ophys_sessions os"
    " LEFT JOIN ophys_experiments oe ON oe.ophys_session_id=os.id" 
    " LEFT JOIN equipment e ON e.id=os.equipment_id JOIN specimens sp ON sp.id=os.specimen_id"
    " LEFT JOIN imaging_depths i ON i.id=oe.imaging_depth_id"
    " LEFT JOIN structures st ON st.id=oe.targeted_structure_id JOIN donors d ON d.id=sp.donor_id"
    f" WHERE os.id = {ophys_session_id} ORDER BY os.id DESC, st.acronym, i.depth, oe.id")[0]
    down_sampled_trace = downsample_array(np.array(roi['trace']),
                                          31,
                                          4,
                                          'average',
                                          seed).tolist()
    down_sampled_trace = down_sampled_trace[:int((len(down_sampled_trace)/10))]
    
    trace_json = {"dataLength": len(down_sampled_trace),
                  "trace": down_sampled_trace}
    
    roi_dict = {'coo_rows': roi['coo_row'],
                'coo_cols': roi['coo_col'],
                'coo_data': roi['coo_data'],
                'image_shape': segmentation_run['video_shape'],
                'experiment_id': segmentation_run['ophys_experiment_id'],
                'roi_id': roi_id,
                'trace': trace_json,
                'rig': meta_data['rig'],
                'depth': meta_data['depth'],
                'full_genotype': meta_data['full_genotype'],
                'targeted_structure': meta_data['targeted_structure'],
                'label': random.randint(0, 1)}
    
    rois.append(roi)

train_set = rois[:70]
test_set = rois[70:]

with open('train_rois.json', 'w') as open_train:
    json.dump(train_set, open_train)

with open('test_rois.json', 'w') as open_test:
    json.dump(test_set, open_test)

with open('train_rois.json', 'r') as open_train:
    loaded_train_rois = json.load(open_train)

with open('test_rois.json', 'r') as open_test:
    loaded_test_rois = json.load(open_test)

if train_set == loaded_train_rois:
    print("Train equivalent to loaded train")
if test_set == loaded_test_rois:
    print("Test equivalent to loaded test")
if train_set[0] == loaded_train_rois[0]:
    print("Train 0 equivalent to loaded train 0")
if test_set[0] == loaded_test_rois[0]:
    print("Test 0 equivalent to loaded test 0")
```

# Validation
I have included in the script validation that the loaded data from the file is equivalent to the data input. I have also examined an individual ROI from both of these files and confirmed they look as expected.

# Notes:
* These are rather large files as the training data is 63mb and the test data is 27mb, this does not appear to be a problem with the writing to json or the data just larger than anticipated. It was originally estimated to be ~1mb but is actually ~100mb  so 100x but still small enough to fit in a repo. If someone sees why it is larger than expected please comment!

### CODE REVIEW

**Comment by kschelonka** [comment]
First thoughts:

Put this in the test folder, not the repo folder please.
These files are huge! This is an order of magnitude larger than expected. Need to investigate.

**Comment by kschelonka** [comment]
For file size:

* Limit the ROIs you choose to ones that are reasonably sized -- there are some here that contain more than 5000 pixels, which is much larger than a real ROI. I suggest an upper limit of 200.
* Use float4.
* Limit the trace to the first say, 200 data points. There's nearly 50000 which is excessive for our purposes.

**Comment by djkapner** [comment]
The binary storage for a mask is 12 bytes/pixel: row (int32 = 4 bytes) col (int32=4 bytes) data (real = 4 bytes) (at least this is true in postgres, things might become 64-bit depending how you read them into python, for example.

json is an ascii format:
your row entry: `219, ` is taking up 5 characters, or 40 bytes. same with column.
your data entry: `0.9525285959243774, ` is taking up 20 characters, or 160 bytes.
so, it is 240 bytes per pixel, or 20x larger than binary.

For test data, you could probably just truncate the data entries, or, you could use some different format. MongoDB uses bson under-the-hood to store json objects. There is a python module, but, ... you might be better off using hdf5 or something.

**Comment by kschelonka** [comment]
@djkapner We can also gzip the files if needed

**Comment by isaak-willett** [comment]
I'm going to truncate the data first as Dan suggested and push it all to float4, the traces were also being read out of the downsample_array function at float64 which was blowing up the size as well. This should reach a manageable size with truncating the data types!

**Comment by djkapner** [comment]
> @djkapner We can also gzip the files if needed

That's true. I wrote this json gzipper that I am quite fond of. If we're going to make a habit of it, we can copy over. It is quite convenient:

https://github.com/AllenInstitute/BigFeta/blob/master/bigfeta/jsongz.py

**Comment by isaak-willett** [comment]
I think I fixed the bug, if you look at my example script above I was accidently adding the ROI object to the list to get written to json not the data dictionary, this was causing the data to be massively over where we thought it would be. I have since corrected that see below my new script for pulling the data. Thanks for the help in identifying this problem
```python
import json
import random

import numpy as np

import allensdk
import slapp.rois as roi_module
from slapp.transforms.array_utils import downsample_array
import slapp.utils.query_utils as query_utils

default_conn_variables = query_utils.label_defaults
db_credentials = query_utils.get_db_credentials(**default_conn_variables)
db_conn = query_utils.DbConnection(**db_credentials)
lims_conn = query_utils.DbConnection(host="limsdb2", database="lims2", port=5432,
                                     user="limsreader", password="limsro")
total_trace_bytes = 0
total_coo_bytes = 0
seed = random.seed(0)
rois = []
for roi_id in range(1574255, 1574355):
    roi_dict = {}
    roi = db_conn.query(f"SELECT * FROM rois WHERE id={roi_id}")[0]
    segmentation_run = db_conn.query(("SELECT * FROM segmentation_runs WHERE "
                                      f"id={roi['segmentation_run_id']}"))[0]
    ophys_experiment_id = segmentation_run['ophys_experiment_id']
    ophys_session_id = lims_conn.query("SELECT ophys_session_id from ophys_experiments"
                                       f" WHERE id={ophys_experiment_id}")[0]['ophys_session_id']
    meta_data = lims_conn.query("SELECT e.name AS rig, i.depth, st.acronym AS targeted_structure," 
    " d.full_genotype FROM ophys_sessions os"
    " LEFT JOIN ophys_experiments oe ON oe.ophys_session_id=os.id" 
    " LEFT JOIN equipment e ON e.id=os.equipment_id JOIN specimens sp ON sp.id=os.specimen_id"
    " LEFT JOIN imaging_depths i ON i.id=oe.imaging_depth_id"
    " LEFT JOIN structures st ON st.id=oe.targeted_structure_id JOIN donors d ON d.id=sp.donor_id"
    f" WHERE os.id = {ophys_session_id} ORDER BY os.id DESC, st.acronym, i.depth, oe.id")[0]
    down_sampled_trace = np.float16(downsample_array(np.array(roi['trace']),
                                          31,
                                          4,
                                          'average',
                                          seed))
    down_sampled_trace = down_sampled_trace[:200]
    total_trace_bytes = total_trace_bytes + down_sampled_trace.nbytes
    total_coo_bytes = total_coo_bytes + np.uint8(roi['coo_row']).nbytes + np.uint8(roi['coo_col']).nbytes + np.float16(roi['coo_data']).nbytes 

    roi_dict = {'coo_rows': np.uint8(roi['coo_row']).tolist(),
                'coo_cols': np.uint8(roi['coo_col']).tolist(),
                'coo_data': np.float16(roi['coo_data']).tolist(),
                'image_shape': segmentation_run['video_shape'],
                'experiment_id': segmentation_run['ophys_experiment_id'],
                'roi_id': roi_id,
                'trace': down_sampled_trace.tolist(),
                'rig': meta_data['rig'],
                'depth': meta_data['depth'],
                'full_genotype': meta_data['full_genotype'],
                'targeted_structure': meta_data['targeted_structure'],
                'label': random.randint(0, 1)}
    rois.append(roi_dict)

print(f"total bytes: {total_coo_bytes + total_trace_bytes}")
print(f"trace type before split: {type(rois[0]['trace'][0])}")
train_set = rois[:70]
test_set = rois[70:]

with open('train_rois.json', 'w') as open_train:
    json.dump(train_set, open_train)

with open('test_rois.json', 'w') as open_test:
    json.dump(test_set, open_test)

with open('train_rois.json', 'r') as open_train:
    loaded_train_rois = json.load(open_train)

with open('test_rois.json', 'r') as open_test:
    loaded_test_rois = json.load(open_test)

if train_set == loaded_train_rois:
    print("Train equivalent to loaded train")
if test_set == loaded_test_rois:
    print("Test equivalent to loaded test")
if train_set[0] == loaded_train_rois[0]:
    print("Train 0 equivalent to loaded train 0")
if test_set[0] == loaded_test_rois[0]:
    print("Test 0 equivalent to loaded test 0")
```

**Comment by njmei** [comment]
Shouldn't the selection of the `roi_id` also be randomized?

**Comment by kschelonka** [comment]
Please also confirm that all categorical labels are present in the train vs. test dataset. Otherwise this will throw an error.

**Comment by isaak-willett** [comment]
I don't think it matters if roi_id is randomized as we aren't using this for anything but testing.

**Comment by isaak-willett** [comment]
Check for existence of all categorical labels:
image

Output from the check:
image

**Comment by kschelonka** [comment]
>Check for existence of all categorical labels:
@isaak-willett I'm referring to the values in the labels.

e.g. 'rig' might be 'Scientifica' or 'Nikon' etc.

**Comment by isaak-willett** [comment]
@kschelonka do you then mean the existence of all the labels we anticipate existing in the actual training and test data?

**Comment by isaak-willett** [comment]
# Changes:
I replaced the two files with two where I randomly selected the ROIs from the Slapp ROI table instead of the top 100. Previously there was an error where the data lacked differences in labels so encoding would not function properly. Selecting random ROIs fixes that error as multiple label values are present for each categorical label.

# Selection Script:
```python
import json
import random

import numpy as np

import allensdk
import slapp.rois as roi_module
from slapp.transforms.array_utils import downsample_array
import slapp.utils.query_utils as query_utils

default_conn_variables = query_utils.label_defaults
db_credentials = query_utils.get_db_credentials(**default_conn_variables)
db_conn = query_utils.DbConnection(**db_credentials)
lims_conn = query_utils.DbConnection(host="limsdb2", database="lims2", port=5432,
                                     user="limsreader", password="limsro")
total_trace_bytes = 0
total_coo_bytes = 0
seed = random.seed(1)
rois = []
start_id = 1574255
table_size = db_conn.query("SELECT id from rois")
table_size = len(table_size)

found_structure_targets = set()
found_rigs = set()
found_genotypes = set()

found_dict = {
        "structure_targets":  found_structure_targets,
        "rigs": found_rigs,
        "genotypes": found_genotypes
        }

for idx in range(0, 100):
    random_idx = random.randint(0, table_size)
    roi_dict = {}
    roi_id = random.randint(0, table_size) + start_id
    roi = db_conn.query(f"SELECT * FROM rois WHERE id={roi_id}")[0]
    segmentation_run = db_conn.query(("SELECT * FROM segmentation_runs WHERE "
                                      f"id={roi['segmentation_run_id']}"))[0]
    ophys_experiment_id = segmentation_run['ophys_experiment_id']
    ophys_session_id = lims_conn.query("SELECT ophys_session_id from ophys_experiments"
                                       f" WHERE id={ophys_experiment_id}")[0]['ophys_session_id']
    meta_data = lims_conn.query("SELECT e.name AS rig, i.depth, st.acronym AS targeted_structure," 
    " d.full_genotype FROM ophys_sessions os"
    " LEFT JOIN ophys_experiments oe ON oe.ophys_session_id=os.id" 
    " LEFT JOIN equipment e ON e.id=os.equipment_id JOIN specimens sp ON sp.id=os.specimen_id"
    " LEFT JOIN imaging_depths i ON i.id=oe.imaging_depth_id"
    " LEFT JOIN structures st ON st.id=oe.targeted_structure_id JOIN donors d ON d.id=sp.donor_id"
    f" WHERE os.id = {ophys_session_id} ORDER BY os.id DESC, st.acronym, i.depth, oe.id")[0]
    down_sampled_trace = np.float16(downsample_array(np.array(roi['trace']),
                                          31,
                                          4,
                                          'average',
                                          seed))
    down_sampled_trace = down_sampled_trace[:200]
    total_trace_bytes = total_trace_bytes + down_sampled_trace.nbytes
    total_coo_bytes = total_coo_bytes + np.uint8(roi['coo_row']).nbytes + np.uint8(roi['coo_col']).nbytes + np.float16(roi['coo_data']).nbytes 

    roi_dict = {'coo_rows': np.uint8(roi['coo_row']).tolist(),
                'coo_cols': np.uint8(roi['coo_col']).tolist(),
                'coo_data': np.float16(roi['coo_data']).tolist(),
                'image_shape': segmentation_run['video_shape'],
                'experiment_id': segmentation_run['ophys_experiment_id'],
                'roi_id': roi_id,
                'trace': down_sampled_trace.tolist(),
                'rig': meta_data['rig'],
                'depth': meta_data['depth'],
                'full_genotype': meta_data['full_genotype'],
                'targeted_structure': meta_data['targeted_structure'],
                'label': random.randint(0, 1)}
    found_structure_targets.add(meta_data['targeted_structure'])
    found_rigs.add(meta_data['rig'])
    found_genotypes.add(meta_data['full_genotype'])
    rois.append(roi_dict)

expected_categorical_keys = ['rig', 'full_genotype', 'targeted_structure', 'label']
missing_categorical_keys = 0
for roi in rois:
    for expected_categorical_key in expected_categorical_keys:
        if expected_categorical_key not in roi or roi[expected_categorical_key] == None:
            missing_categorical_keys += 1

print(f"Total missing categorical key definitions: {missing_categorical_keys}")
print(f"Found categorical labels: {found_dict}")
print(f"total bytes: {total_coo_bytes + total_trace_bytes}")
print(f"trace type before split: {type(rois[0]['trace'][0])}")
train_set = rois[:70]
test_set = rois[70:]


with open('train_rois.json', 'w') as open_train:
    json.dump(train_set, open_train)

with open('test_rois.json', 'w') as open_test:
    json.dump(test_set, open_test)

with open('train_rois.json', 'r') as open_train:
    loaded_train_rois = json.load(open_train)

with open('test_rois.json', 'r') as open_test:
    loaded_test_rois = json.load(open_test)

if train_set == loaded_train_rois:
    print("Train equivalent to loaded train")
if test_set == loaded_test_rois:
    print("Test equivalent to loaded test")
if train_set[0] == loaded_train_rois[0]:
    print("Train 0 equivalent to loaded train 0")
if test_set[0] == loaded_test_rois[0]:
    print("Test 0 equivalent to loaded test 0")
```
# Validation:
The categorical labels present are captured in the below screenshot
image

**Comment by kschelonka** [comment]
You are still not ensuring that the values in categorical keys exist in both the train and test sets.

Example:

Train data:
| rig         | label |
|-------------|-------|
| scientifica | 1     |
| nikon       | 0     |
| scientifica | 1     |

Test data:
| rig         | label |
|-------------|-------|
| scientifica | 1     |
| nikon       | 0     |
| awesome_rig | 1     |

Will raise a `ValueError` during one-hot-encoding because "awesome_rig" isn't a category for the rig feature in the training data.

**Comment by isaak-willett** [comment]
@kschelonka oh that's my mistake I was mistaken on what you wanted. I validated the data with the following script and the files currently uploaded contain the same labels in both sets.
# Script
```python
import json
import random

import numpy as np

import allensdk
import slapp.rois as roi_module
from slapp.transforms.array_utils import downsample_array
import slapp.utils.query_utils as query_utils

default_conn_variables = query_utils.label_defaults
db_credentials = query_utils.get_db_credentials(**default_conn_variables)
db_conn = query_utils.DbConnection(**db_credentials)
lims_conn = query_utils.DbConnection(host="limsdb2", database="lims2", port=5432,
                                     user="limsreader", password="limsro")
total_trace_bytes = 0
total_coo_bytes = 0
seed = random.seed(1)
train_set = []
start_id = 1574255
table_size = db_conn.query("SELECT id from rois")
table_size = len(table_size)

found_structure_targets = set()
found_rigs = set()
found_genotypes = set()
found_test_targets = set()
found_test_rigs = set()
found_test_genotypes = set()

found_dict = {
        "structure_targets":  found_structure_targets,
        "rigs": found_rigs,
        "genotypes": found_genotypes,
        "test structure_targets": found_test_targets,
        "test rigs": found_test_rigs,
        "test genotypes": found_test_genotypes
        }

for idx in range(0, 70):
    random_idx = random.randint(0, table_size)
    roi_dict = {}
    roi_id = random.randint(0, table_size) + start_id
    roi = db_conn.query(f"SELECT * FROM rois WHERE id={roi_id}")[0]
    segmentation_run = db_conn.query(("SELECT * FROM segmentation_runs WHERE "
                                      f"id={roi['segmentation_run_id']}"))[0]
    ophys_experiment_id = segmentation_run['ophys_experiment_id']
    ophys_session_id = lims_conn.query("SELECT ophys_session_id from ophys_experiments"
                                       f" WHERE id={ophys_experiment_id}")[0]['ophys_session_id']
    meta_data = lims_conn.query("SELECT e.name AS rig, i.depth, st.acronym AS targeted_structure," 
    " d.full_genotype FROM ophys_sessions os"
    " LEFT JOIN ophys_experiments oe ON oe.ophys_session_id=os.id" 
    " LEFT JOIN equipment e ON e.id=os.equipment_id JOIN specimens sp ON sp.id=os.specimen_id"
    " LEFT JOIN imaging_depths i ON i.id=oe.imaging_depth_id"
    " LEFT JOIN structures st ON st.id=oe.targeted_structure_id JOIN donors d ON d.id=sp.donor_id"
    f" WHERE os.id = {ophys_session_id} ORDER BY os.id DESC, st.acronym, i.depth, oe.id")[0]
    down_sampled_trace = np.float16(downsample_array(np.array(roi['trace']),
                                          31,
                                          4,
                                          'average',
                                          seed))
    down_sampled_trace = down_sampled_trace[:200]
    total_trace_bytes = total_trace_bytes + down_sampled_trace.nbytes
    total_coo_bytes = total_coo_bytes + np.uint8(roi['coo_row']).nbytes + np.uint8(roi['coo_col']).nbytes + np.float16(roi['coo_data']).nbytes 

    roi_dict = {'coo_rows': np.uint8(roi['coo_row']).tolist(),
                'coo_cols': np.uint8(roi['coo_col']).tolist(),
                'coo_data': np.float16(roi['coo_data']).tolist(),
                'image_shape': segmentation_run['video_shape'],
                'experiment_id': segmentation_run['ophys_experiment_id'],
                'roi_id': roi_id,
                'trace': down_sampled_trace.tolist(),
                'rig': meta_data['rig'],
                'depth': meta_data['depth'],
                'full_genotype': meta_data['full_genotype'],
                'targeted_structure': meta_data['targeted_structure'],
                'label': random.randint(0, 1)}
    found_structure_targets.add(meta_data['targeted_structure'])
    found_rigs.add(meta_data['rig'])
    found_genotypes.add(meta_data['full_genotype'])
    train_set.append(roi_dict)

test_set = []
test_cnt = 0

while test_cnt < 30:
    all_labels_in_train = False
    while not all_labels_in_train:
       random_idx = random.randint(0, table_size)
       roi_dict = {}
       roi_id = random.randint(0, table_size) + start_id
       roi = db_conn.query(f"SELECT * FROM rois WHERE id={roi_id}")[0]
       segmentation_run = db_conn.query(("SELECT * FROM segmentation_runs WHERE "
                                      f"id={roi['segmentation_run_id']}"))[0]
       ophys_experiment_id = segmentation_run['ophys_experiment_id']
       ophys_session_id = lims_conn.query("SELECT ophys_session_id from ophys_experiments"
                                       f" WHERE id={ophys_experiment_id}")[0]['ophys_session_id']
       meta_data = lims_conn.query("SELECT e.name AS rig, i.depth, st.acronym AS targeted_structure," 
       " d.full_genotype FROM ophys_sessions os"
       " LEFT JOIN ophys_experiments oe ON oe.ophys_session_id=os.id" 
       " LEFT JOIN equipment e ON e.id=os.equipment_id JOIN specimens sp ON sp.id=os.specimen_id"
       " LEFT JOIN imaging_depths i ON i.id=oe.imaging_depth_id"
       " LEFT JOIN structures st ON st.id=oe.targeted_structure_id JOIN donors d ON d.id=sp.donor_id"
       f" WHERE os.id = {ophys_session_id} ORDER BY os.id DESC, st.acronym, i.depth, oe.id")[0]
       if meta_data['rig'] in found_rigs and meta_data['targeted_structure'] in found_structure_targets and meta_data['full_genotype'] in found_genotypes:
           all_labels_in_train = True
    down_sampled_trace = np.float16(downsample_array(np.array(roi['trace']),
                                          31,
                                          4,
                                          'average',
                                          seed))
    down_sampled_trace = down_sampled_trace[:200]
    total_trace_bytes = total_trace_bytes + down_sampled_trace.nbytes
    total_coo_bytes = total_coo_bytes + np.uint8(roi['coo_row']).nbytes + np.uint8(roi['coo_col']).nbytes + np.float16(roi['coo_data']).nbytes 

    roi_dict = {'coo_rows': np.uint8(roi['coo_row']).tolist(),
                'coo_cols': np.uint8(roi['coo_col']).tolist(),
                'coo_data': np.float16(roi['coo_data']).tolist(),
                'image_shape': segmentation_run['video_shape'],
                'experiment_id': segmentation_run['ophys_experiment_id'],
                'roi_id': roi_id,
                'trace': down_sampled_trace.tolist(),
                'rig': meta_data['rig'],
                'depth': meta_data['depth'],
                'full_genotype': meta_data['full_genotype'],
                'targeted_structure': meta_data['targeted_structure'],
                'label': random.randint(0, 1)}
    found_test_targets.add(meta_data['targeted_structure'])
    found_test_rigs.add(meta_data['rig'])
    found_test_genotypes.add(meta_data['full_genotype'])
    test_set.append(roi_dict)
    test_cnt += 1

print(f"Found keys from training and testing: {found_dict}")

with open('train_rois.json', 'w') as open_train:
    json.dump(train_set, open_train)

with open('test_rois.json', 'w') as open_test:
    json.dump(test_set, open_test)

with open('train_rois.json', 'r') as open_train:
    loaded_train_rois = json.load(open_train)

with open('test_rois.json', 'r') as open_test:
    loaded_test_rois = json.load(open_test)

if train_set == loaded_train_rois:
    print("Train equivalent to loaded train")
if test_set == loaded_test_rois:
    print("Test equivalent to loaded test")
if train_set[0] == loaded_train_rois[0]:
    print("Train 0 equivalent to loaded train 0")
if test_set[0] == loaded_test_rois[0]:
    print("Test 0 equivalent to loaded test 0")
```

**Pull request merged**
